---
- name: "Copy banner file to '{{ sshd_banner['path'] }}'"
  tags: sshd.banner.copy
  ansible.builtin.copy:
    src: banner
    dest: "{{ sshd_banner['path'] }}"
    owner: "{{ sshd_banner['owner'] }}"
    group: "{{ sshd_banner['group'] }}"
    mode: "{{ sshd_banner['mode'] }}"
    setype: "{{ sshd_banner['setype'] }}"
  become: true

- name: "Set Banner parameter in '{{ sshd_config['path'] }}'"
  tags: sshd.banner.config
  ansible.builtin.lineinfile:
    path: "{{ sshd_config['path'] }}"
    regexp: "^#*Banner"
    line: "Banner {{ sshd_banner['path'] }}"
    validate: sshd -t -f %s
  become: true
  notify: "Restart sshd service"
