- name: Disable passing user's LC_* variables in sshd_config
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: "{{ item }}"
    line: "#{{ item }}"
  loop:
    - "AcceptEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES"
    - "AcceptEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT"
    - "AcceptEnv LC_IDENTIFICATION LC_ALL LANGUAGE"
  notify: "Restart ssh service"
