---
- name: "Create subdirectories of '{{ test_dir }}' required for test"
  ansible.builtin.file:
    state: directory
    path: "{{ test_dir }}{{ item | dirname }}"
  loop: "{{ test_files }}"
  loop_control:
    label: "{{ test_dir }}{{ item }}"

- name: "Copy config file to '{{ test_dir }}{{ sshd_config['path'] }}'"
  ansible.builtin.copy:
    src: "{{ sshd_config['path'] }}"
    dest: "{{ test_dir }}{{ sshd_config['path'] }}"
    owner: "{{ sshd_banner['owner'] }}"
    group: "{{ sshd_banner['group'] }}"
    mode: "{{ sshd_banner['mode'] }}"
    setype: "{{ sshd_banner['setype'] }}"
    remote_src: true
